//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQPlayer.ResourceFiles.SettingsResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralTabResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralTabResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DQPlayer.ResourceFiles.SettingsResources.GeneralTabResources", typeof(GeneralTabResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string AppearanceHeader {
            get {
                return ResourceManager.GetString("AppearanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageHeader {
            get {
                return ResourceManager.GetString("LanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menus Language:.
        /// </summary>
        public static string MenusLanguageLabel {
            get {
                return ResourceManager.GetString("MenusLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow only one instance.
        /// </summary>
        public static string OneInstanceCB {
            get {
                return ResourceManager.GetString("OneInstanceCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use only one instance when started from file manager.
        /// </summary>
        public static string OneInstancesFromFMCB {
            get {
                return ResourceManager.GetString("OneInstancesFromFMCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause on the last frame of a video.
        /// </summary>
        public static string PauseOnLastFrameCB {
            get {
                return ResourceManager.GetString("PauseOnLastFrameCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause when minimised.
        /// </summary>
        public static string PauseWhenMinimisedCB {
            get {
                return ResourceManager.GetString("PauseWhenMinimisedCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist and Instances.
        /// </summary>
        public static string PlaylistAndInstancesHeader {
            get {
                return ResourceManager.GetString("PlaylistAndInstancesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show controls in full screen mode.
        /// </summary>
        public static string ShowControlsInFSCB {
            get {
                return ResourceManager.GetString("ShowControlsInFSCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show icon in system tray.
        /// </summary>
        public static string ShowIconInSystray {
            get {
                return ResourceManager.GetString("ShowIconInSystray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin:.
        /// </summary>
        public static string SkinLabel {
            get {
                return ResourceManager.GetString("SkinLabel", resourceCulture);
            }
        }
    }
}
