//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DQPlayer.ResourceFiles.SettingsResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VideoTabResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VideoTabResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DQPlayer.ResourceFiles.SettingsResources.VideoTabResources", typeof(VideoTabResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always fit window.
        /// </summary>
        public static string AlwaysFitWindowCB {
            get {
                return ResourceManager.GetString("AlwaysFitWindowCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect ratio.
        /// </summary>
        public static string AspectRatioLB {
            get {
                return ResourceManager.GetString("AspectRatioLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        public static string DisplayHeader {
            get {
                return ResourceManager.GetString("DisplayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable video.
        /// </summary>
        public static string EnableVideoCB {
            get {
                return ResourceManager.GetString("EnableVideoCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide cursor in fullscreen after x seconds.
        /// </summary>
        public static string HideCursorInFullscreenLB {
            get {
                return ResourceManager.GetString("HideCursorInFullscreenLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position of video title.
        /// </summary>
        public static string PositionOfVideoTitleLB {
            get {
                return ResourceManager.GetString("PositionOfVideoTitleLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show media title on video.
        /// </summary>
        public static string ShowMediaTitleCB {
            get {
                return ResourceManager.GetString("ShowMediaTitleCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show video title for x milliseconds.
        /// </summary>
        public static string ShowTitleForMSLB {
            get {
                return ResourceManager.GetString("ShowTitleForMSLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video snapshot directory.
        /// </summary>
        public static string SnapshotDirectoryLB {
            get {
                return ResourceManager.GetString("SnapshotDirectoryLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video snapshot format.
        /// </summary>
        public static string SnapshotFormatLB {
            get {
                return ResourceManager.GetString("SnapshotFormatLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapshot.
        /// </summary>
        public static string SnapshotHeader {
            get {
                return ResourceManager.GetString("SnapshotHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video snapshot file prefix.
        /// </summary>
        public static string SnapshotPrefixLB {
            get {
                return ResourceManager.GetString("SnapshotPrefixLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start in fullscreen.
        /// </summary>
        public static string StartInFullscreenCB {
            get {
                return ResourceManager.GetString("StartInFullscreenCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video cropping.
        /// </summary>
        public static string VideoCroppingLB {
            get {
                return ResourceManager.GetString("VideoCroppingLB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Properties.
        /// </summary>
        public static string WindowPropertiesHeader {
            get {
                return ResourceManager.GetString("WindowPropertiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string ZoomLB {
            get {
                return ResourceManager.GetString("ZoomLB", resourceCulture);
            }
        }
    }
}
